server:
  port: 8802
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=GMT%2B8
    username: root
    password: 1026263358
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show-sql: true

#  security:
#    user:
#      password: 123456
#      name: test
logging:
  path: logs
#      roles: